// <auto-generated />
using System;
using ICMarkets.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ICMarkets.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413101846_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ICMarkets.Domain.Entities.BlockchainData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("BaseFee")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("BlockTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Height")
                        .HasColumnType("bigint");

                    b.Property<long?>("HighFeePerKb")
                        .HasColumnType("bigint");

                    b.Property<long?>("HighGasPrice")
                        .HasColumnType("bigint");

                    b.Property<long?>("HighPriorityFee")
                        .HasColumnType("bigint");

                    b.Property<string>("LastForkHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("LastForkHeight")
                        .HasColumnType("bigint");

                    b.Property<string>("LatestUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long?>("LowFeePerKb")
                        .HasColumnType("bigint");

                    b.Property<long?>("LowGasPrice")
                        .HasColumnType("bigint");

                    b.Property<long?>("LowPriorityFee")
                        .HasColumnType("bigint");

                    b.Property<long?>("MediumFeePerKb")
                        .HasColumnType("bigint");

                    b.Property<long?>("MediumGasPrice")
                        .HasColumnType("bigint");

                    b.Property<long?>("MediumPriorityFee")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("PeerCount")
                        .HasColumnType("integer");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PreviousUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("UnconfirmedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Network", "Chain", "CreatedAt")
                        .IsDescending(false, false, true);

                    b.ToTable("blockchain_data", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
